server:
  port: 8088

#druid config ref:https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter

spring:
  datasource:
    druid:
      url: "jdbc:mysql://localhost:3306/test1015?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false"
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 200
      initial-size: 3
      min-idle: 3
      max-wait: 600000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false

